### ISSUE TITLE
Integrate slam/auto nav 

### ISSUE THREAD

**Issue by WilliamBaltus** [Ekumen-OS/andino_gz#41]
## Desired behavior
Similar to your andino repo running gazebo classic, is it possible to integrate the slam_toolbox and nav2 usage into this? 

## Alternatives considered
Would it make sense to just copy those packages over and edit the launch file? I'm new to ROS2.

## Implementation suggestion
I couldn't tell you any implementation suggestions.

## Additional context
Basically I would just like the gazebo classic functionality from the andino repo available with gazebo fortress. If copying over isn't viable or efficient please let me know!

**Comment by francocipollone** [comment]
@WilliamBaltus A slam example has been added. If you want to use nav2 you can create a map doing slam and then with that map you can launch nav2 via nav2_bringup package. 

We might add in the future some direct examples with that

**Comment by francocipollone** [comment]
Superseded by https://github.com/Ekumen-OS/andino_gz/issues/49

**Comment by WilliamBaltus** [comment]
This is phenomenal, thank you so much franco. Cloning now, will report back

**Comment by WilliamBaltus** [comment]
Example works like a charm, flawless. Thank you!
