### ISSUE TITLE
Should andino_gz.launch.py also open rviz2?

### ISSUE THREAD

**Issue by WilliamBaltus** [Ekumen-OS/andino_gz#42]
## Environment
* OS Version: Ubuntu 22.04
* Raspberry Pi 4
* ROS 2 Humble
* Gazebo Fortress
* Source or binary build?
Source build, latest main

## Description
* Expected behavior: I ran the launch file and I am wondering if should also see RViz2 pop up. I edited launch file to use rviz2 but to no avail.
* Actual behavior: Fortress launches fine, I can view lidar using gui as shown in media in readMe.

## Steps to reproduce

1.Followed ReadMe to run andino_gz.launch.py

## Output
Described in actual behavior

## Additional Context
I am unsure if RViz should  open on its own, new to ROS2, but reading the launch file I think it should? If I launch rviz2 myself from different terminal how may I connect the data to the gazebo? When I did launch rviz myself it did seem to inherit the config file in the rviz folder but I could not get points from the camera nor the lidar. Am I supposed to run some commands and use ros_ign_bridge to get the data from the sensors to something that can be visualized on Rviz? Any advice may help, thanks!

**Comment by francocipollone** [comment]
Hey there! Gazebo can work on its own without being integrated to ROS2 and that's why by default the launch file only launches the simulation, spwan a robot and that's it.

If you want to run the ros bridge you can automatically do so by indicating this via flag:
```
ros2 launch andino_gz andino_gz.launch.py ros_bridge:=true
```

If you want to also run rviz2 pass the correspondent flag
```
ros2 launch andino_gz andino_gz.launch.py ros_bridge:=true rviz:=true
```

**Comment by WilliamBaltus** [comment]
Gotcha, I ran the bottom command and rviz2 did in fact launch! However there were issues with the wheels in robot model stating that 

"No transform from [left_wheel] to [X]"
 (the same for right wheel, castor rotation, and castor wheel)

with X being the selected fixed frame. 


Lastly, how do I visualize the lidar in rviz? Because I am able to view in gazebo gui using visualize_lidar but unsure how to get that data into rviz? I thought changing the fixed frame would do it... thanks for help!

**Comment by francocipollone** [comment]
> Gotcha, I ran the bottom command and rviz2 did in fact launch! However there were issues with the wheels in robot model stating that
> 
> "No transform from [left_wheel] to [X]" (the same for right wheel, castor rotation, and castor wheel)
> 

That's because the simulation hasn't started. Once the simulation starts the correspondent transformations (e.g: left_wheel / right_wheel ) are published


> Lastly, how do I visualize the lidar in rviz? Because I am able to view in gazebo gui using visualize_lidar but unsure how to get that data into rviz? I thought changing the fixed frame would do it... thanks for help!

Actually, there was a bug I just fixed: #45  . Once this is merged, just verify you are using the latest changes

**Comment by WilliamBaltus** [comment]
You got it. Merging today and will report.

**Comment by WilliamBaltus** [comment]
Works like a charm! The wheels don't really load but that's okay with me, just note. I think good to close.

**Comment by francocipollone** [comment]
> Works like a charm! The wheels don't really load but that's okay with me, just note. I think good to close.

Feel free to post here what you are getting, I don't see that issue with the wheels on my end

**Comment by WilliamBaltus** [comment]
Nvm it works fine. Sometimes the transforms aren't found but simply pressing play in gazebo fixes this. Or just giving more time for things to load (pi4 is slow.) Lots of times it is not working jsust fine from the start.

**Comment by francocipollone** [comment]
> Nvm it works fine. Sometimes the transforms aren't found but simply pressing play in gazebo fixes this. Or just giving more time for things to load (pi4 is slow.) Lots of times it is not working jsust fine from the start.

Wow, are you running the sim using a raspi? (I know you provided that information but I didn't realize the raspberry) I didn't expect that! Great to know it works well in a raspi as well
