### ISSUE TITLE
ROS: Revisit frame for /scan publishing

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino_gz#43]
### Issue

![image](https://github.com/Ekumen-OS/andino_gz/assets/53065142/de76ea35-543c-4939-bf11-5c77530728c5)

The message uses a frame id that doesn't much with tf tree

**Comment by WilliamBaltus** [comment]
Wait what is the issue?

**Comment by francocipollone** [comment]
Check:

 - gz_frame_id: https://github.com/gazebosim/gz-sensors/blob/ign-sensors6/src/Sensor.cc#L152
