### ISSUE TITLE
Create Jazzy branch to support ROS Jazzy + Harmonic

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [Ekumen-OS/andino_gz#71]
## Desired behavior
To be able to support ROS 2 Jazzy, we will need to have support on `andino_gz` for Gazebo Harmonic

## Implementation suggestion
Some notes:

 - Migrate ign namespace to gz (it is doable in humble/fortress)
 - We need a Jazzy branch
 - We need a docker ubuntu 24 with Jazzy + Harmonic
 - Migrate name of plugins if needed to harmonic

**Comment by JesusSilvaUtrera** [comment]
@francocipollone FYI

**Comment by francocipollone** [comment]
FYI @JesusSilvaUtrera See https://github.com/Ekumen-OS/andino_gz/issues/72

We will need to migrate to harmonic also for humble.

**Comment by JesusSilvaUtrera** [comment]
Closing issue since PR got merged
