### ISSUE TITLE
Lidar isn't working correctly in Gazebo Fortress

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino_gz#72]
## Environment
* OS Version: Ubuntu 22.04
* Source

## Description
* Expected behavior: Lidar messages are correctly
* Actual behavior: Getting inf in lidar messages in certain ocations.

## Steps to reproduce
1. `ros2 launch andino_gz  andino_gz.launch.py world_name:=depot.sdf`
2. `Add visualize lidar' GUI 
3. `Rotate or move the andino using teleop`

You can see the wrong lectures using the GUI plugin or
 - checking the topic: ign topic -t /world/gazebo_world/model/andino/link/base_link/sensor/sensor_ray_front/scan -e
 - checking rviz's lidar visualization

## Output

[Screencast from 08-09-2024 02:53:33 PM.webm](https://github.com/user-attachments/assets/ee7b1082-e350-42e4-b56f-717671b35d7a)

**Comment by francocipollone** [comment]
It sounds like a bug in Fortress
It is not happening in Gazebo Harmonic (I just saved the world and launch it with `gz sim`)

[Screencast from 08-09-2024 03:13:02 PM.webm](https://github.com/user-attachments/assets/5572a6d7-a4a6-48e9-b3b2-c6e831cc9c28)

**Comment by francocipollone** [comment]
Indeed: https://github.com/gazebosim/gz-sim/issues/1112

**Comment by francocipollone** [comment]
Tried using harmonic real quick, works good:

![image](https://github.com/user-attachments/assets/443d9ee1-2f43-4cc2-a3e4-b135065c5f76)

I just used the unofficial ros binaries `ros-humble-gzharmonic` (see https://gazebosim.org/docs/harmonic/ros_installation/#gazebo-harmonic-with-ros-2-humble-iron-or-rolling-use-with-caution) to install the `ros_gz` bridge for `humble-harmonic`

We need to migrate to harmonic, it is a pity we won't be able to release andino_gz for humble due to this non-ros provided dependency.

**Comment by JesusSilvaUtrera** [comment]
Regarding this is also necessary, it would make sense to begin by migrating the `humble` branch to Harmonic, right @francocipollone? And then begin with the `Jazzy + Harmonic` branch.

**Comment by francocipollone** [comment]
> Regarding this is also necessary, it would make sense to begin by migrating the `humble` branch to Harmonic, right @francocipollone? And then begin with the `Jazzy + Harmonic` branch.

Correct!

**Comment by francocipollone** [comment]
Reopening as this issue was being caused by the visual meshes interfering with the lidars. 
In our case the lidar meshes shouldn't interfere with the lidar sensor, in order to do so we need the mesh to not have internal normals, as the lidar sensor does not have a clipping plane parameter or something like that.

In harmonic the behavior seems to be different and that's why in harmonic it was working correctly.

I'd like to support Humble-Fortress combination so I will evaluate how we can fix this.

**Comment by francocipollone** [comment]
Closed as resolved
