### ISSUE TITLE
Flickering Issue in Gazebo Ignition Fortress with GPU

### ISSUE THREAD

**Issue by SAJIB3489** [Ekumen-OS/andino_gz#87]
## Environment
* OS Version: 22.04 (jammy-20240808)
* Git clone: https://github.com/Ekumen-OS/andino_gz.git -b 0.1.1

## Description
I am encountering a **Flickering**  issue when using the NVIDIA GPU for simulation in Gazebo Ignition Fortress (version 6.16.0). The flickering disappears if I do not use the GPU, but the simulation becomes very slow. I am running the simulation inside a Docker container with a GUI via noVNC.

## System Details:
* Gazebo Version: Fortress 6.16.0
* NVIDIA GPU Model: Tesla P100 PCIe 16GB
* Driver Version: 535.183.01
* CUDA Version: 12.2
* OpenGL Version: 4.6 (GLSL 4.6)

### Dockerfile for gazebo installation:
```bash
RUN sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list' && \
    wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add - && \
    apt-get update -q && \
    apt-get upgrade -y && \
    apt-get install -y \
    ros-${ROS_DISTRO}-navigation2 \
    ros-${ROS_DISTRO}-turtle-nest \
    ros-${ROS_DISTRO}-ros-gz-sim \
    ros-${ROS_DISTRO}-ros-gz-bridge \
    ignition-fortress
```
### Docker Container Command
```bash
docker run --restart=always -d \
    -e VNC_PASSWORD=1234 \
    -e USER=sajib \
    -e PASSWORD=1234 \
    -e ROS_DOMAIN_ID=1 \
    -e NVIDIA_DRIVER_CAPABILITIES=all \
    -e __GLX_VENDOR_LIBRARY_NAME=nvidia \
    -v "/home/sajib/22":/home/sajib \
    -v /dev/dri:/dev/dri \
    -p 6555:80 \
    -p 6556:22 \
    --security-opt seccomp=unconfined \
    --shm-size=4gb \
    --gpus all \
    --runtime=nvidia \
    image_name:latest
```
### Approaches Attempted:
1. Disabled cast shadows in the world model (SDF):
```bash
<cast_shadows>false</cast_shadows>
<cast_shadows>0</cast_shadows>
```
2. Modified ~/.ignition/gazebo/6/gui.config:
```bash
<engine>ogre</engine>
```
[Video Link](https://drive.google.com/file/d/1iL7KZoWPVoFMZAqSJP3pp3ob6rKd3tl6/view?usp=sharing)

Any suggestions or solutions would be greatly appreciated.

**Comment by francocipollone** [comment]
Hey there @SAJIB3489 , I haven't heard about this issue before, is it possible to try the sim in other "situations" just to discard that it is an issue with your image/container or an issue with the andino simulation setup:
 1. In your container, open just gazebo: `ign gazebo` and open a gazebo demo world, and check if it still happens.
 2. Try using provided docker setup: https://github.com/Ekumen-OS/andino_gz/tree/humble/docker
 3. Try running the sim in the host (if you have an ubuntu 22) simply do `sudo apt install ros-humble-andino-gz` for installing it. ( you need to have ros2 humble installed)
 

So
 - if after trying 1 you still see the issue, it is not andino related.
 - if using the provided docker (2) fixes the issue, then it is an issue with the custom image/container.
 - if running in host (3) fixes the issue, then there is an issue with the containerization.

**Comment by SAJIB3489** [comment]
Thank you for your suggestion and quick response. The issue was with the Docker image itself. I tested a different image, and it **worked smoothly without any problems**.

I’ll go ahead and close this issue. Have a great day!
