### ISSUE TITLE
After building dokcer image and running container, andino_gz is not installed - branch jazzy

### ISSUE THREAD

**Issue by daniel-lopez-puig** [Ekumen-OS/andino_gz#89]
## Environment
OS Version: Ubuntu 24.04 
source build - jazzy - last commit: 030c8f340b9a42c10d40edb46935a2a08b51d6aa

## Description
Expected behavior: 
git clone this repo and checkout to branch jazzy
run the script to build iamge
run the script to run container
package is installed properly into workind directory (ws/install) and you can source it using `source ./install/setup.bash`

I think the issue is related to permissions but during docker build process using the script no error arise so I really don't know what to try more.

Actual behavior: 
inside container:` ~/ws/install` is empty

## Steps to reproduce

1. git clone git@github.com:Ekumen-OS/andino_gz.git
2. cd andino_gz
3. git checkout jazzy
4.  ./docker/build.sh
5.  ./docker/run.sh
6.  source ./install/setup.bash -> file doesn't exist

## Output
![image](https://github.com/user-attachments/assets/27a82f01-38cb-46ce-9378-a6b91dde31ef)
![image](https://github.com/user-attachments/assets/1fbadf2c-44f0-4b75-8b06-03381bc47841)

More info related to permissions inside docker:
![image](https://github.com/user-attachments/assets/1f652649-c457-40ae-b76f-593e3985d101)

**Comment by francocipollone** [comment]
Hey there @daniel-lopez-puig . The install folder will be empty at start. You need to colcon build and then you source the install folder.

Regarding permissions. The install folder shouldn't be root otherwise the colcon build won't be able to modify that folder. I will take a look.

**Comment by francocipollone** [comment]
@daniel-lopez-puig Take a look at it now. https://github.com/Ekumen-OS/andino_gz/pull/90 should have fixed the permissions issue.

**Comment by daniel-lopez-puig** [comment]
@francocipollone Thanks for the quick fix! It works for me now!
